### ISSUE TITLE
HDF5 error while loading data

### ISSUE THREAD

**Issue by jgiemza** [guilopgar/GeneExpImgTL#2]
Hello,

I find your method very interesting and I wanted to explore this repository. Unfortunately while executing 1-KEGG_BRITE_Hierarchy.ipynb, I got the error below after executing second cell. (I downloaded the data from the link provided in PanCancer folder). I will be grateful for our help !

---------------------------------------------------------------------------
HDF5ExtError                              Traceback (most recent call last)
~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    654         try:
--> 655             self._handle = tables.open_file(self._path, self._mode, **kwargs)
    656         except IOError as err:  # pragma: no cover

~/anaconda3/lib/python3.8/site-packages/tables/file.py in open_file(filename, mode, title, root_uep, filters, **kwargs)
    314     # Finally, create the File instance, and return it
--> 315     return File(filename, mode, title, root_uep, filters, **kwargs)
    316 

~/anaconda3/lib/python3.8/site-packages/tables/file.py in __init__(self, filename, mode, title, root_uep, filters, **kwargs)
    777         # Now, it is time to initialize the File extension
--> 778         self._g_new(filename, mode, **params)
    779 

tables/hdf5extension.pyx in tables.hdf5extension.File._g_new()

HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 37, error message = 'No locks available'

End of HDF5 error back trace

Unable to open/create file 'data/PanCancer/mad_filter_pancan_all_TCGA_20.h5'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    395             raise FileNotFoundError(f"File {path_or_buf} does not exist")
    396 
--> 397         store = HDFStore(path_or_buf, mode=mode, errors=errors, **kwargs)
    398         # can't auto open/close if we are using an iterator
    399         # so delegate to the iterator

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in __init__(self, path, mode, complevel, complib, fletcher32, **kwargs)
    535         self._fletcher32 = fletcher32
    536         self._filters = None
--> 537         self.open(mode=mode, **kwargs)
    538 
    539     def __fspath__(self):

~/anaconda3/lib/python3.8/site-packages/pandas/io/pytables.py in open(self, mode, **kwargs)
    685             # is not part of IOError, make it one
    686             if self._mode == "r" and "Unable to open/create file" in str(err):
--> 687                 raise IOError(str(err))
    688             raise
    689 

OSError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 37, error message = 'No locks available'

End of HDF5 error back trace

Unable to open/create file 'data/PanCancer/mad_filter_pancan_all_TCGA_20.h5'

**Comment by matsutakk** [comment]
Hi from Japan.

I faced the same problem, so I downloaded original data and preprocessed it.

[Here it is](https://github.com/matsutakk/pancancer), I think you can produce same data.
